// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: action_manager.proto

package accessibility_bridge_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionKey_Key int32

const (
	ActionKey_UNKNOWN                                    ActionKey_Key = 0
	ActionKey_GLOBAL_ACTION_BACK                         ActionKey_Key = 1
	ActionKey_GLOBAL_ACTION_HOME                         ActionKey_Key = 2
	ActionKey_GLOBAL_ACTION_RECENTS                      ActionKey_Key = 3
	ActionKey_GLOBAL_ACTION_NOTIFICATIONS                ActionKey_Key = 4
	ActionKey_GLOBAL_ACTION_QUICK_SETTINGS               ActionKey_Key = 5
	ActionKey_GLOBAL_ACTION_POWER_DIALOG                 ActionKey_Key = 6
	ActionKey_GLOBAL_ACTION_TOGGLE_SPLIT_SCREEN          ActionKey_Key = 7
	ActionKey_GLOBAL_ACTION_LOCK_SCREEN                  ActionKey_Key = 8
	ActionKey_GLOBAL_ACTION_TAKE_SCREENSHOT              ActionKey_Key = 9
	ActionKey_GLOBAL_ACTION_KEYCODE_HEADSETHOOK          ActionKey_Key = 10
	ActionKey_GLOBAL_ACTION_ACCESSIBILITY_BUTTON         ActionKey_Key = 11
	ActionKey_GLOBAL_ACTION_ACCESSIBILITY_BUTTON_CHOOSER ActionKey_Key = 12
	ActionKey_GLOBAL_ACTION_ACCESSIBILITY_SHORTCUT       ActionKey_Key = 13
	ActionKey_GLOBAL_ACTION_ACCESSIBILITY_ALL_APPS       ActionKey_Key = 14
	ActionKey_GLOBAL_ACTION_DISMISS_NOTIFICATION_SHADE   ActionKey_Key = 15
	ActionKey_GLOBAL_ACTION_DPAD_UP                      ActionKey_Key = 16
	ActionKey_GLOBAL_ACTION_DPAD_DOWN                    ActionKey_Key = 17
	ActionKey_GLOBAL_ACTION_DPAD_LEFT                    ActionKey_Key = 18
	ActionKey_GLOBAL_ACTION_DPAD_RIGHT                   ActionKey_Key = 19
	ActionKey_GLOBAL_ACTION_DPAD_CENTER                  ActionKey_Key = 20
)

// Enum value maps for ActionKey_Key.
var (
	ActionKey_Key_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "GLOBAL_ACTION_BACK",
		2:  "GLOBAL_ACTION_HOME",
		3:  "GLOBAL_ACTION_RECENTS",
		4:  "GLOBAL_ACTION_NOTIFICATIONS",
		5:  "GLOBAL_ACTION_QUICK_SETTINGS",
		6:  "GLOBAL_ACTION_POWER_DIALOG",
		7:  "GLOBAL_ACTION_TOGGLE_SPLIT_SCREEN",
		8:  "GLOBAL_ACTION_LOCK_SCREEN",
		9:  "GLOBAL_ACTION_TAKE_SCREENSHOT",
		10: "GLOBAL_ACTION_KEYCODE_HEADSETHOOK",
		11: "GLOBAL_ACTION_ACCESSIBILITY_BUTTON",
		12: "GLOBAL_ACTION_ACCESSIBILITY_BUTTON_CHOOSER",
		13: "GLOBAL_ACTION_ACCESSIBILITY_SHORTCUT",
		14: "GLOBAL_ACTION_ACCESSIBILITY_ALL_APPS",
		15: "GLOBAL_ACTION_DISMISS_NOTIFICATION_SHADE",
		16: "GLOBAL_ACTION_DPAD_UP",
		17: "GLOBAL_ACTION_DPAD_DOWN",
		18: "GLOBAL_ACTION_DPAD_LEFT",
		19: "GLOBAL_ACTION_DPAD_RIGHT",
		20: "GLOBAL_ACTION_DPAD_CENTER",
	}
	ActionKey_Key_value = map[string]int32{
		"UNKNOWN":                                    0,
		"GLOBAL_ACTION_BACK":                         1,
		"GLOBAL_ACTION_HOME":                         2,
		"GLOBAL_ACTION_RECENTS":                      3,
		"GLOBAL_ACTION_NOTIFICATIONS":                4,
		"GLOBAL_ACTION_QUICK_SETTINGS":               5,
		"GLOBAL_ACTION_POWER_DIALOG":                 6,
		"GLOBAL_ACTION_TOGGLE_SPLIT_SCREEN":          7,
		"GLOBAL_ACTION_LOCK_SCREEN":                  8,
		"GLOBAL_ACTION_TAKE_SCREENSHOT":              9,
		"GLOBAL_ACTION_KEYCODE_HEADSETHOOK":          10,
		"GLOBAL_ACTION_ACCESSIBILITY_BUTTON":         11,
		"GLOBAL_ACTION_ACCESSIBILITY_BUTTON_CHOOSER": 12,
		"GLOBAL_ACTION_ACCESSIBILITY_SHORTCUT":       13,
		"GLOBAL_ACTION_ACCESSIBILITY_ALL_APPS":       14,
		"GLOBAL_ACTION_DISMISS_NOTIFICATION_SHADE":   15,
		"GLOBAL_ACTION_DPAD_UP":                      16,
		"GLOBAL_ACTION_DPAD_DOWN":                    17,
		"GLOBAL_ACTION_DPAD_LEFT":                    18,
		"GLOBAL_ACTION_DPAD_RIGHT":                   19,
		"GLOBAL_ACTION_DPAD_CENTER":                  20,
	}
)

func (x ActionKey_Key) Enum() *ActionKey_Key {
	p := new(ActionKey_Key)
	*p = x
	return p
}

func (x ActionKey_Key) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionKey_Key) Descriptor() protoreflect.EnumDescriptor {
	return file_action_manager_proto_enumTypes[0].Descriptor()
}

func (ActionKey_Key) Type() protoreflect.EnumType {
	return &file_action_manager_proto_enumTypes[0]
}

func (x ActionKey_Key) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionKey_Key.Descriptor instead.
func (ActionKey_Key) EnumDescriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{8, 0}
}

type ScreenView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Bounds        *ScreenView_Bounds     `protobuf:"bytes,4,opt,name=bounds,proto3" json:"bounds,omitempty"`
	Children      []*ScreenView          `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	UniqueId      string                 `protobuf:"bytes,6,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenView) Reset() {
	*x = ScreenView{}
	mi := &file_action_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenView) ProtoMessage() {}

func (x *ScreenView) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenView.ProtoReflect.Descriptor instead.
func (*ScreenView) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{0}
}

func (x *ScreenView) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScreenView) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ScreenView) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ScreenView) GetBounds() *ScreenView_Bounds {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *ScreenView) GetChildren() []*ScreenView {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ScreenView) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

type ElementSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniqueId      string                 `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Regex         string                 `protobuf:"bytes,4,opt,name=regex,proto3" json:"regex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementSelector) Reset() {
	*x = ElementSelector{}
	mi := &file_action_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementSelector) ProtoMessage() {}

func (x *ElementSelector) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementSelector.ProtoReflect.Descriptor instead.
func (*ElementSelector) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ElementSelector) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *ElementSelector) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_action_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Finger struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FingerId int32                  `protobuf:"varint,1,opt,name=finger_id,json=fingerId,proto3" json:"finger_id,omitempty"`
	// Types that are valid to be assigned to Start:
	//
	//	*Finger_StartPoint
	//	*Finger_StartElement
	Start         isFinger_Start `protobuf_oneof:"start"`
	Width         uint32         `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32         `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Duration      int32          `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	KeepDown      bool           `protobuf:"varint,7,opt,name=keep_down,json=keepDown,proto3" json:"keep_down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finger) Reset() {
	*x = Finger{}
	mi := &file_action_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finger) ProtoMessage() {}

func (x *Finger) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finger.ProtoReflect.Descriptor instead.
func (*Finger) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{3}
}

func (x *Finger) GetFingerId() int32 {
	if x != nil {
		return x.FingerId
	}
	return 0
}

func (x *Finger) GetStart() isFinger_Start {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Finger) GetStartPoint() *Point {
	if x != nil {
		if x, ok := x.Start.(*Finger_StartPoint); ok {
			return x.StartPoint
		}
	}
	return nil
}

func (x *Finger) GetStartElement() *ElementSelector {
	if x != nil {
		if x, ok := x.Start.(*Finger_StartElement); ok {
			return x.StartElement
		}
	}
	return nil
}

func (x *Finger) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Finger) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Finger) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Finger) GetKeepDown() bool {
	if x != nil {
		return x.KeepDown
	}
	return false
}

type isFinger_Start interface {
	isFinger_Start()
}

type Finger_StartPoint struct {
	StartPoint *Point `protobuf:"bytes,100,opt,name=start_point,json=startPoint,proto3,oneof"`
}

type Finger_StartElement struct {
	StartElement *ElementSelector `protobuf:"bytes,101,opt,name=start_element,json=startElement,proto3,oneof"`
}

func (*Finger_StartPoint) isFinger_Start() {}

func (*Finger_StartElement) isFinger_Start() {}

type ActionSwipe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finger        *Finger                `protobuf:"bytes,1,opt,name=finger,proto3" json:"finger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSwipe) Reset() {
	*x = ActionSwipe{}
	mi := &file_action_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSwipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSwipe) ProtoMessage() {}

func (x *ActionSwipe) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSwipe.ProtoReflect.Descriptor instead.
func (*ActionSwipe) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{4}
}

func (x *ActionSwipe) GetFinger() *Finger {
	if x != nil {
		return x.Finger
	}
	return nil
}

type ActionMultiTouch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finger        []*Finger              `protobuf:"bytes,1,rep,name=finger,proto3" json:"finger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionMultiTouch) Reset() {
	*x = ActionMultiTouch{}
	mi := &file_action_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionMultiTouch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionMultiTouch) ProtoMessage() {}

func (x *ActionMultiTouch) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionMultiTouch.ProtoReflect.Descriptor instead.
func (*ActionMultiTouch) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{5}
}

func (x *ActionMultiTouch) GetFinger() []*Finger {
	if x != nil {
		return x.Finger
	}
	return nil
}

type ActionClick struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Click:
	//
	//	*ActionClick_ClickPoint
	//	*ActionClick_ClickElement
	Click         isActionClick_Click `protobuf_oneof:"click"`
	Duration      int32               `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionClick) Reset() {
	*x = ActionClick{}
	mi := &file_action_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionClick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionClick) ProtoMessage() {}

func (x *ActionClick) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionClick.ProtoReflect.Descriptor instead.
func (*ActionClick) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ActionClick) GetClick() isActionClick_Click {
	if x != nil {
		return x.Click
	}
	return nil
}

func (x *ActionClick) GetClickPoint() *Point {
	if x != nil {
		if x, ok := x.Click.(*ActionClick_ClickPoint); ok {
			return x.ClickPoint
		}
	}
	return nil
}

func (x *ActionClick) GetClickElement() *ElementSelector {
	if x != nil {
		if x, ok := x.Click.(*ActionClick_ClickElement); ok {
			return x.ClickElement
		}
	}
	return nil
}

func (x *ActionClick) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type isActionClick_Click interface {
	isActionClick_Click()
}

type ActionClick_ClickPoint struct {
	ClickPoint *Point `protobuf:"bytes,100,opt,name=click_point,json=clickPoint,proto3,oneof"`
}

type ActionClick_ClickElement struct {
	ClickElement *ElementSelector `protobuf:"bytes,101,opt,name=click_element,json=clickElement,proto3,oneof"`
}

func (*ActionClick_ClickPoint) isActionClick_Click() {}

func (*ActionClick_ClickElement) isActionClick_Click() {}

type ActionTypeText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *ElementSelector       `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionTypeText) Reset() {
	*x = ActionTypeText{}
	mi := &file_action_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionTypeText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionTypeText) ProtoMessage() {}

func (x *ActionTypeText) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionTypeText.ProtoReflect.Descriptor instead.
func (*ActionTypeText) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{7}
}

func (x *ActionTypeText) GetSelector() *ElementSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *ActionTypeText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ActionKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           ActionKey_Key          `protobuf:"varint,1,opt,name=key,proto3,enum=service.accessibility.bridge.ActionKey_Key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionKey) Reset() {
	*x = ActionKey{}
	mi := &file_action_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionKey) ProtoMessage() {}

func (x *ActionKey) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionKey.ProtoReflect.Descriptor instead.
func (*ActionKey) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{8}
}

func (x *ActionKey) GetKey() ActionKey_Key {
	if x != nil {
		return x.Key
	}
	return ActionKey_UNKNOWN
}

type ScreenView_Bounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          int32                  `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Top           int32                  `protobuf:"varint,2,opt,name=top,proto3" json:"top,omitempty"`
	Right         int32                  `protobuf:"varint,3,opt,name=right,proto3" json:"right,omitempty"`
	Bottom        int32                  `protobuf:"varint,4,opt,name=bottom,proto3" json:"bottom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenView_Bounds) Reset() {
	*x = ScreenView_Bounds{}
	mi := &file_action_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenView_Bounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenView_Bounds) ProtoMessage() {}

func (x *ScreenView_Bounds) ProtoReflect() protoreflect.Message {
	mi := &file_action_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenView_Bounds.ProtoReflect.Descriptor instead.
func (*ScreenView_Bounds) Descriptor() ([]byte, []int) {
	return file_action_manager_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ScreenView_Bounds) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *ScreenView_Bounds) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *ScreenView_Bounds) GetRight() int32 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *ScreenView_Bounds) GetBottom() int32 {
	if x != nil {
		return x.Bottom
	}
	return 0
}

var File_action_manager_proto protoreflect.FileDescriptor

const file_action_manager_proto_rawDesc = "" +
	"\n" +
	"\x14action_manager.proto\x12\x1cservice.accessibility.bridge\"\xd9\x02\n" +
	"\n" +
	"ScreenView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12G\n" +
	"\x06bounds\x18\x04 \x01(\v2/.service.accessibility.bridge.ScreenView.BoundsR\x06bounds\x12D\n" +
	"\bchildren\x18\x05 \x03(\v2(.service.accessibility.bridge.ScreenViewR\bchildren\x12\x1b\n" +
	"\tunique_id\x18\x06 \x01(\tR\buniqueId\x1a\\\n" +
	"\x06Bounds\x12\x12\n" +
	"\x04left\x18\x01 \x01(\x05R\x04left\x12\x10\n" +
	"\x03top\x18\x02 \x01(\x05R\x03top\x12\x14\n" +
	"\x05right\x18\x03 \x01(\x05R\x05right\x12\x16\n" +
	"\x06bottom\x18\x04 \x01(\x05R\x06bottom\"D\n" +
	"\x0fElementSelector\x12\x1b\n" +
	"\tunique_id\x18\x01 \x01(\tR\buniqueId\x12\x14\n" +
	"\x05regex\x18\x04 \x01(\tR\x05regex\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xb3\x02\n" +
	"\x06Finger\x12\x1b\n" +
	"\tfinger_id\x18\x01 \x01(\x05R\bfingerId\x12F\n" +
	"\vstart_point\x18d \x01(\v2#.service.accessibility.bridge.PointH\x00R\n" +
	"startPoint\x12T\n" +
	"\rstart_element\x18e \x01(\v2-.service.accessibility.bridge.ElementSelectorH\x00R\fstartElement\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12\x1b\n" +
	"\tkeep_down\x18\a \x01(\bR\bkeepDownB\a\n" +
	"\x05start\"K\n" +
	"\vActionSwipe\x12<\n" +
	"\x06finger\x18\x01 \x01(\v2$.service.accessibility.bridge.FingerR\x06finger\"P\n" +
	"\x10ActionMultiTouch\x12<\n" +
	"\x06finger\x18\x01 \x03(\v2$.service.accessibility.bridge.FingerR\x06finger\"\xd0\x01\n" +
	"\vActionClick\x12F\n" +
	"\vclick_point\x18d \x01(\v2#.service.accessibility.bridge.PointH\x00R\n" +
	"clickPoint\x12T\n" +
	"\rclick_element\x18e \x01(\v2-.service.accessibility.bridge.ElementSelectorH\x00R\fclickElement\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bdurationB\a\n" +
	"\x05click\"o\n" +
	"\x0eActionTypeText\x12I\n" +
	"\bselector\x18\x01 \x01(\v2-.service.accessibility.bridge.ElementSelectorR\bselector\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x89\x06\n" +
	"\tActionKey\x12=\n" +
	"\x03key\x18\x01 \x01(\x0e2+.service.accessibility.bridge.ActionKey.KeyR\x03key\"\xbc\x05\n" +
	"\x03Key\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x16\n" +
	"\x12GLOBAL_ACTION_BACK\x10\x01\x12\x16\n" +
	"\x12GLOBAL_ACTION_HOME\x10\x02\x12\x19\n" +
	"\x15GLOBAL_ACTION_RECENTS\x10\x03\x12\x1f\n" +
	"\x1bGLOBAL_ACTION_NOTIFICATIONS\x10\x04\x12 \n" +
	"\x1cGLOBAL_ACTION_QUICK_SETTINGS\x10\x05\x12\x1e\n" +
	"\x1aGLOBAL_ACTION_POWER_DIALOG\x10\x06\x12%\n" +
	"!GLOBAL_ACTION_TOGGLE_SPLIT_SCREEN\x10\a\x12\x1d\n" +
	"\x19GLOBAL_ACTION_LOCK_SCREEN\x10\b\x12!\n" +
	"\x1dGLOBAL_ACTION_TAKE_SCREENSHOT\x10\t\x12%\n" +
	"!GLOBAL_ACTION_KEYCODE_HEADSETHOOK\x10\n" +
	"\x12&\n" +
	"\"GLOBAL_ACTION_ACCESSIBILITY_BUTTON\x10\v\x12.\n" +
	"*GLOBAL_ACTION_ACCESSIBILITY_BUTTON_CHOOSER\x10\f\x12(\n" +
	"$GLOBAL_ACTION_ACCESSIBILITY_SHORTCUT\x10\r\x12(\n" +
	"$GLOBAL_ACTION_ACCESSIBILITY_ALL_APPS\x10\x0e\x12,\n" +
	"(GLOBAL_ACTION_DISMISS_NOTIFICATION_SHADE\x10\x0f\x12\x19\n" +
	"\x15GLOBAL_ACTION_DPAD_UP\x10\x10\x12\x1b\n" +
	"\x17GLOBAL_ACTION_DPAD_DOWN\x10\x11\x12\x1b\n" +
	"\x17GLOBAL_ACTION_DPAD_LEFT\x10\x12\x12\x1c\n" +
	"\x18GLOBAL_ACTION_DPAD_RIGHT\x10\x13\x12\x1d\n" +
	"\x19GLOBAL_ACTION_DPAD_CENTER\x10\x14b\x06proto3"

var (
	file_action_manager_proto_rawDescOnce sync.Once
	file_action_manager_proto_rawDescData []byte
)

func file_action_manager_proto_rawDescGZIP() []byte {
	file_action_manager_proto_rawDescOnce.Do(func() {
		file_action_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_manager_proto_rawDesc), len(file_action_manager_proto_rawDesc)))
	})
	return file_action_manager_proto_rawDescData
}

var file_action_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_action_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_action_manager_proto_goTypes = []any{
	(ActionKey_Key)(0),        // 0: service.accessibility.bridge.ActionKey.Key
	(*ScreenView)(nil),        // 1: service.accessibility.bridge.ScreenView
	(*ElementSelector)(nil),   // 2: service.accessibility.bridge.ElementSelector
	(*Point)(nil),             // 3: service.accessibility.bridge.Point
	(*Finger)(nil),            // 4: service.accessibility.bridge.Finger
	(*ActionSwipe)(nil),       // 5: service.accessibility.bridge.ActionSwipe
	(*ActionMultiTouch)(nil),  // 6: service.accessibility.bridge.ActionMultiTouch
	(*ActionClick)(nil),       // 7: service.accessibility.bridge.ActionClick
	(*ActionTypeText)(nil),    // 8: service.accessibility.bridge.ActionTypeText
	(*ActionKey)(nil),         // 9: service.accessibility.bridge.ActionKey
	(*ScreenView_Bounds)(nil), // 10: service.accessibility.bridge.ScreenView.Bounds
}
var file_action_manager_proto_depIdxs = []int32{
	10, // 0: service.accessibility.bridge.ScreenView.bounds:type_name -> service.accessibility.bridge.ScreenView.Bounds
	1,  // 1: service.accessibility.bridge.ScreenView.children:type_name -> service.accessibility.bridge.ScreenView
	3,  // 2: service.accessibility.bridge.Finger.start_point:type_name -> service.accessibility.bridge.Point
	2,  // 3: service.accessibility.bridge.Finger.start_element:type_name -> service.accessibility.bridge.ElementSelector
	4,  // 4: service.accessibility.bridge.ActionSwipe.finger:type_name -> service.accessibility.bridge.Finger
	4,  // 5: service.accessibility.bridge.ActionMultiTouch.finger:type_name -> service.accessibility.bridge.Finger
	3,  // 6: service.accessibility.bridge.ActionClick.click_point:type_name -> service.accessibility.bridge.Point
	2,  // 7: service.accessibility.bridge.ActionClick.click_element:type_name -> service.accessibility.bridge.ElementSelector
	2,  // 8: service.accessibility.bridge.ActionTypeText.selector:type_name -> service.accessibility.bridge.ElementSelector
	0,  // 9: service.accessibility.bridge.ActionKey.key:type_name -> service.accessibility.bridge.ActionKey.Key
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_action_manager_proto_init() }
func file_action_manager_proto_init() {
	if File_action_manager_proto != nil {
		return
	}
	file_action_manager_proto_msgTypes[3].OneofWrappers = []any{
		(*Finger_StartPoint)(nil),
		(*Finger_StartElement)(nil),
	}
	file_action_manager_proto_msgTypes[6].OneofWrappers = []any{
		(*ActionClick_ClickPoint)(nil),
		(*ActionClick_ClickElement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_manager_proto_rawDesc), len(file_action_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_manager_proto_goTypes,
		DependencyIndexes: file_action_manager_proto_depIdxs,
		EnumInfos:         file_action_manager_proto_enumTypes,
		MessageInfos:      file_action_manager_proto_msgTypes,
	}.Build()
	File_action_manager_proto = out.File
	file_action_manager_proto_goTypes = nil
	file_action_manager_proto_depIdxs = nil
}
